%% Digital Control Systems Homework #2
%% Problem 1
% Find the $z$-transforms of the number sequences generated by sampling the 
% following time functions every $T$ seconds, beginning at t = 0. Express these 
% transforms in closed form. 
% (a) $e\left(t\right)=\exp \left(-\textrm{at}\right)$
% From this expression, since we are sampling every $T$ seconds we can replace 
% the term $t$ with $t = kT$ and we can include a _unit step_ function into the 
% expression since we are concerned with beginning from $t=0$ onward:
% 
% $$e\left(t\right)=e\left(\textrm{kT}\right)=e^{-\textrm{akT}} u\left(k\right)$$
% 
% Expressing this in closed form, we get:
% 
% $$Z\left\lbrace e\left(\textrm{kT}\right)\right\rbrace =\sum_{k=0}^{\infty 
% } e\left(\textrm{kT}\right)z^{-k}$$
% 
% $$\begin{array}{l}\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=\sum_{k=0}^{\infty 
% } e^{-a\;k\;T} z^{-k} \\\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=\sum_{k=0}^{\infty 
% } {\left(e^{-a\;T} z^{-1} \right)}^k \end{array}$$
% 
% $E\left(z\right)=\frac{1}{1-e^{-a\;T} z^{-1} }$ or $\frac{z}{z-e^{-a\;T} },\;\;\;\;\;\;\;\;\;\textrm{for}\;\;\;|e^{-a\;T} 
% z^{-1} |<1$

% Prove with MATLAB
syms a k t T
et = exp(-a*t)
ekT = subs(et,t,k*T)
Ez = ztrans(ekT)
% (a) $e\left(t\right)=\exp \left(-t+T\right)u\left(t-T\right)$
% $$e\left(t\right)=e^{-t+T} u\left(t-T\right)$$
% 
% Replace the term $t$ with the sampling interval $t\to$$kT$
% 
% $$e(kT) = e^{-kT + T}u(kT-T) = e^{-(k-1)T}u((k-1)T)$$
% 
% Using the $z$-transform property for a Time-Shift:
% 
% $$z\left\lbrace e\left(k-n\right)u\left(k-n\right)\right\rbrace =z^{-n} E\left(z\right)$$
% 
% which illustrates that the original $z$-transform of $e\left(k\right)$ is 
% multiplied by a factor of $z^{-n}$ depending on the shift term. The closed-form 
% expression results in:
% 
% $z\{ e^{-(k-1)T}u((k-1)T)\} = z^{-1}E(z) =  z^{-1}\left[\frac{z}{z-e^{-T}}\right]  
% = \frac{1}{z-e^{-T}}$,      for $|e^{-T} z^{-1} |<1$

% Prove with MATLAB
syms z k t T
et = exp(-t)
ekT = subs(et,t,k*T)
Ez = ztrans(ekT)
Ez = (z^-1) * Ez
% (a) $e\left(t\right)=\exp \left(-t+5T\right)u\left(t-5T\right)$
% This expression follows the same operations as the previous question, but 
% has a larger delay. Following the same steps previously, we get:
% 
% $$e\left(t\right)=e^{-t+5T} u\left(t-5T\right)$$
% 
% Replace the term $t$ with the sampling interval $t\to$$kT$
% 
% $$e(kT) = e^{-kT + 5T}u(kT-5T) = e^{-(k-5)T}u((k-5)T)$$
% 
% Again, using the $z$-transform property for a Time-Shift yields:
% 
% $z\{ e^{-(k-5)T}u((k-5)T)\} = z^{-5}E(z) =  z^{-5}\left[\frac{z}{z-e^{-T}}\right]  
% = \frac{1}{z^4(z-e^{-T})}$,      for $|e^{-T} z^{-1} |<1$

% Prove with MATLAB
syms k t T
et = exp(-t)
ekT = subs(et,t,k*T)
Ez = ztrans(ekT)
Ez = (z^-5) * Ez
%% Problem 2
% A function e(t) is sampled, and the resultant sequence has the z-transform
% 
% $$E(z) = \frac{z-b}{z^3-cz^2+d}$$
% 
% Find the $z$-transform of exp($akT$)$e(kT)$
% 
% This problem is asking us to solve for the $z$-transform of exp($akT$)$e(kT)$, 
% which involves using the $z$-transform property of Complex Translation, that 
% is:
% 
% $$z\left\lbrace \varepsilon^{\textrm{akT}} e\left(\textrm{kT}\right)\right\rbrace 
% =e\left(0\right)+\varepsilon^{\textrm{aT}} e\left(T\right)z^{-1} +\varepsilon^{2\textrm{aT}} 
% e\left(2T\right)z^{-2} +\;\ldotp \ldotp \ldotp$$
% 
% $$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=e\left(0\right)+e\left(T\right){\left(z\varepsilon^{-\textrm{aT}} 
% \right)}^{-1} +e\left(2T\right){\left(z\varepsilon^{-\textrm{aT}} \right)}^{-2} 
% +\;\ldotp \ldotp \ldotp$$
% 
% or
% 
% $$z \{ \varepsilon^{akT} e(kT)\} = E(z)_{z\leftarrow z\varepsilon^{-aT}} = 
% E(z \varepsilon^{-aT})$$
% 
% Thus, we can solve this problem using this property, which essentially states 
% that we replace all terms of $z$ in $E\left(z\right)$ with the term $z\varepsilon^{-\textrm{aT}}$
% 
% $$E(z) \bigg\vert _{z\leftarrow z \varepsilon^{-aT}} = \frac{z-b}{z^3 -cz^2 
% + d} \bigg\vert _{z\leftarrow z \varepsilon^{-aT}} = \frac{z\varepsilon^{-aT} 
% -b}{z^3\varepsilon^{-aT} -cz^2\varepsilon^{-aT} +d}$$
% 
% Thus, using the property of Complex Translation and $E\left(z\right)$, we 
% can solve for exp($akT$)$e(kT)$ 

syms a b c d T z 
% Use property of Complex Translation to replace values of z for ze^-aT
Ez = (z-b)/(z^3 -c*z^2 + d)
Ez = subs(Ez,z,z*exp(-a*T))
%% Problem 3
% For the number sequence $\left\lbrace e\left(k\right)\right\rbrace$,
% 
% $$E\left(z\right)=\frac{z}{{\left(z-1\right)}^2 }$$
% 
% *(a)* Apply the final-value theorem to $E\left(z\right)$
% 
% The final-value theorem states that $\lim_{k\to \infty } e\left(k\right)=\lim_{z\to 
% 1} \;\left(z-1\right)E\left(z\right)$ if $e\left(\infty \right)$ exists. When 
% examining $E\left(z\right)$, we use the transform pair to find the inverse transform 
% is equal to:
% 
% $z^{-1} \left\lbrace E\left(z\right)\right\rbrace =\frac{z}{{\left(z-1\right)}^2 
% }\;=\;k\;$then, finding $e\left(\infty \right)$ in our case is rather simple 
% since this sequence linearly increases in values, so:
% 
% $\lim_{k\to \infty } e\left(k\right)=\infty$, which it's limit is unbounded. 
% 
% Thus, we cannot use the final-value theorem because all the poles of $E\left(z\right)$ 
% are not inside the unit circle.
% 
% Double-checking in the z-Domain, we find:
% 
% $$\lim_{k\to \infty } e\left(k\right)=\lim_{z\to 1} \;\left(z-1\right)E\left(z\right)$$
% 
% $$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=$$$$\lim_{z\to 1} \;\left(z-1\right)\frac{z}{{\left(z-1\right)}^2 
% }$$
% 
% $$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=$$$$\lim_{z\to 1} \;\frac{z}{{\left(z-1\right)} 
% }$$
% 
% $$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=$$$$\lim_{z\to 1} \;\frac{1}{{\left(1-1\right)} 
% }=\frac{1}{0}=\textrm{indeterminate}\;$$

syms k z
Ez1 = z/(z-1)^2
ek1 = iztrans(Ez1,k)
ek_final_value = subs(ek1,k,Inf)
%% 
% *(b)* Find the $z$-transform of $e\left(k\right)={k\left(-1\right)}^k$
% 
% For this problem, we can use the transform pair:
% 
% $$ka^k \leftrightarrow \frac{az}{(z-a)^2}$$
% 
% In our case, $a=-1,$ which results in the z-transform:
% 
% $$z\{e(k)\} = z\{k(-1)^k\} = -\frac{z}{(z+1)^2}$$
% 
% Thus,
% 
% $$E\left(z\right)=-\frac{z}{{\left(z+1\right)}^2 }$$

% Prove using MATLAB
syms k z
ek2 = k*(-1)^k
Ez2 = ztrans(ek2)
%% 
% *(c)* Explain how parts(a) and (b) are related
% 
% From part (a), we showed that the final-value theorem for $E\left(z\right)$ 
% was unbounded. 
% 
% So, now we check if $e\left(\infty \right)$ exists for part (b)
% 
% $\lim_{k\to \infty } e\left(k\right)={k\left(-1\right)}^k \to \lim_{k\to \infty 
% } {\infty \left(-1\right)}^{\infty }$ which results in an unbounded result 
% 
% So, here for the case of part (b), the value of $e\left(\infty \right)$ is 
% unbounded as well, which means that it doesn't exist either
% 
% So, we conclude that both parts (a) and (b) are related due to both of their 
% time-domai signals at $e\left(\infty \right)$ not existing when taking their 
% corresponding limits. This means that we cannot take the final-value theorem 
% approach for these sequences because all of their poles for $E\left(z\right)$ 
% are not within the unit circle. In fact, part (a) has double poles at $z=1$ 
% and part (b) has double poles at $z=-1,$ which is exactly on the unit circle 
% and explains our findings. 
% 
%